In [1]:
import torch
print(torch.__version__)

2.0.1+cu118


In [2]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


## Intro to Tensors

In [3]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
#Get tensor back as python int
scalar.item()

7

In [7]:
#vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [8]:
vector.ndim

1

In [9]:
vector.shape

torch.Size([2])

In [10]:
#matrix
matrix = torch.tensor([[7, 8], [9, 10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [11]:
matrix.ndim

2

In [12]:
matrix.shape

torch.Size([2, 2])

In [16]:
#TENSOR
TENSOR = torch.tensor([[[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[1, 2, 3], [4, 5, 6], [7, 8, 9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [17]:
TENSOR.ndim

3

In [18]:
TENSOR.shape

torch.Size([2, 3, 3])

In [22]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [23]:
#Random Tensors
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.5209, 0.7947, 0.4799, 0.1589],
        [0.1388, 0.5859, 0.4217, 0.1894],
        [0.4061, 0.8599, 0.8290, 0.1233]])

In [24]:
random_tensor.ndim

2

In [26]:
t = torch.arange(10)

In [28]:
ten_zeros = torch.zeros_like(t)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [29]:
ten_zeros.type(torch.float32)

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

## Reshaping, stacking and unsqueezing tensors

View of tensor shares same memore of tensor, i.e changing a view changes the original

In [38]:
 import torch
 x = torch.arange(1., 10.)
 x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [39]:
#Add extra dim
x_reshaped = x.reshape(1, 9)
x_reshaped

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [40]:
#Change view
z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [41]:
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [44]:
# Stack tensors on top of each other
x_stacked =  torch.stack([x, x, x, x], dim=1)
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [46]:
x_reshaped.shape

torch.Size([1, 9])

In [47]:
x_reshaped.squeeze()

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [48]:
x_reshaped.squeeze().shape

torch.Size([9])

In [49]:
# torch.permute rearranges the dims in  a specified order
x_original = torch.randn(size = (224, 224, 3)) # (B, H, C)
x_permuted = x_original.permute(2, 0, 1) # (C, B, H)
x_original.shape, x_permuted.shape

(torch.Size([224, 224, 3]), torch.Size([3, 224, 224]))

In [55]:
x_original[0, 0, 0] = 0
x_permuted[0, 0, 0]

tensor(0.)

In [59]:
x[0] = 1.
x

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [63]:
z1 = x.view(1, 3, 3)
z1

tensor([[[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]])

In [66]:
z1[0][2][2], z1[:, :, 2]

(tensor(9.), tensor([[3., 6., 9.]]))

In [67]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'
device

'cpu'

In [69]:
x.to(device)
x

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])